Fixed missing system modules in app wrapper after upgrade to Python 3.6 (#474)
After upgrading to Python 3.6 [using brew], moneyGuru kept crashing on
startup. The error was:

> File "build/moneyGuru.app/Contents/Resources/py/encodings/__init__.py",
  line 31, in <module>
> ModuleNotFoundError: No module named 'codecs'

The problem was that none of the system modules had been copied into the app
wrapper becuse the path to them -- as supplied by get_path('stdlib') in
sysconfig.py -- included a symlink that made the path not match exactly what
hscommon/build.py's collect_stdlib_dependencies expected.

Simple fix: Normalize the path using os.path.realpath before comparing with
it.